### ISSUE TITLE
配置错误

### ISSUE THREAD

**Issue by jayliang701** [anjia0532/discovery-syncer#1]
你好。
以docker 模式启动，有以下错误：
```bash
2023-05-01 05:19:26.816 [Error] load configuration error:yaml: unmarshal errors:

  line 3: field enable-pprof not found in type config.Config

  line 53: field upstream-prefix not found in type config.plain

  line 55: field name not found in type config.plain

  line 57: field maximum-interval-sec not found in type config.plain
```

目前的配置文件如下：
```yaml
# 是否启用 pprof
# 通过 http://ip:port/debug/pprof/ 访问
enable-pprof: false
logger:
    level: info # debug,info,error
    logger: console # console vs file
    log-file: syncer.log # The file name of the logger output, does not exist automatically
    date-slice: y # Cut the document by date, support "y" (year), "m" (month), "d" (day), "h" (hour), default "y".

# 注册中心,map形式
discovery-servers:
    # nacos 是注册中心的名字，可以随便定义，但是不能重复
    nacos:
        # 类型，目前仅支持 nacos和eureka
        type: nacos
        # 默认，如果注册中心没有返回权重时，添加的默认权重
        weight: 100
        # 注册中心的url前缀
        prefix: /nacos/v1/
        # 注册中心的连接地址，注意最后不能带/
        host: "http://host.docker.internal:8858"

# 网关,map形式
gateway-servers:
    # 网关名字，可以随便写，但是不能重复
    apisix:
        # 网关类型，目前支持apisix和kong
        type: apisix
        # 管理端host,注意最后不能有/
        admin-url: http://host.docker.internal:9080
        # 管理端uri前缀
        prefix: /apisix/admin/
        # 特别的扩展参数，在config里用key:value形式添加
        config:
            X-API-KEY: edd1c9f034335f136f87ad84b625c8f1

# 同步任务，列表形式
targets:
    # 注意同一个注册中心，但是有多个租户（类似nacos的命名空间）时，不需要创建多个相同的注册中心
    # 只需要创建多个targets，然后改config的扩展参数即可
    # 第一个任务
    # 注册中心，来源
    -   discovery: nacos
        # 网关，目标
        gateway: apisix
        # 是否启用
        enabled: true
        # 拉取间隔，具体支持表达式，详见 https://github.com/robfig/cron
        fetch-interval: "@every 10s"
        # 默认是把能拉倒的注册中心的服务都拉过来，有些不需要的，则进行排除,支持正则
        # exclude-service: [ 'ex*','test' ]
        # 同步到网关的upstream的名字的前缀，便于管理
        upstream-prefix: nacos-edo-dev
        # 本次同步唯一key，为空则是discovery-gateway
        name: nacos-edo-dev
        # 对于health检查时，超过限定秒数的，认为是失联状态，默认是10秒
        maximum-interval-sec: 20
        # 扩展参数
        config:
            # nacos 的groupName
            groupName: DEFAULT_GROUP
            # nacos的 namespace
            namespaceId: edo-dev
            # 创建到apisix 的upstream的默认模板，具体支持的模板语法，自行搜索 golang text/template
            template: |
                {
                    "id": "syncer-{{.Name}}",
                    "timeout": {
                        "connect": 30,
                        "send": 30,
                        "read": 30
                    },
                    "name": "{{.Name}}",
                    "nodes": {{.Nodes}},
                    "type":"roundrobin",
                    "desc": "auto sync by https://github.com/anjia0532/discovery-syncer"
                }
```

请问如何解决? 谢谢!
